image: mknaack/azure-cosmos-db-base:0.9

pipelines:
  default:
    - step:
        script:
          - eval $(opam config env)
          - dune runtest --instrument-with bisect_ppx --force
          - bisect-ppx-report coveralls coverage.json
          - codecov -f coverage.json -t ${CODECOV_TOKEN}
