definitions:
  caches:
    opam-downloads: ~/.opam/download-cache
    opam-repo: ~/.opam/repo
    opam-switch408: ~/.opam/4.08

pipelines:
  default:
    - step:
        name: Build image and test
        image: ocaml/opam:alpine-ocaml-4.08
        caches:
          - opam-downloads
          - opam-repo
          - opam-switch408
        script:
          - sudo apk add --update gmp-dev libev-dev openssl-dev zlib-dev gnupg coreutils
          - curl -Os https://uploader.codecov.io/latest/alpine/codecov
          - chmod +x codecov
          - sudo mv codecov /usr/bin/
          - opam install . --deps-only --with-test
          - eval $(opam config env)
          - dune runtest --instrument-with bisect_ppx --force
          - bisect-ppx-report coveralls coverage.json
          - codecov -f coverage.json -t ${CODECOV_TOKEN}
