image: ocaml/opam2

pipelines:
  default:
    - step:
        caches:
          - opam
        script:
          - eval $(opam config env)
          - opam update
          - opam pin add -yn azure-cosmos-db .
          - opam install -t azure-cosmos-db

definitions:
  caches:
    opam: ~/.opam/