name: Build and test

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          # - "4.8"
          - "5.3"
        # allow-prerelease-opam:
        #   - true
        # opam-repositories:
        #   - |-
        #     default: https://github.com/ocaml/opam-repository.git

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          # allow-prerelease-opam: ${{ matrix.allow-prerelease-opam }}
          # opam-repositories: ${{ matrix.opam-repositories }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - run: opam exec -- bisect-ppx-report coveralls coverage.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
