name: Build and test

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-core:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - "5.3"
          - "4.12"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install core dependencies
        run: opam install ./azure-cosmos-db.opam --deps-only --with-test

      - name: Build core package
        run: opam exec -- dune build -p azure-cosmos-db

  build-lwt:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - "5.3"
          - "4.12"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install lwt dependencies
        run: opam install ./azure-cosmos-db.opam ./azure-cosmos-db-lwt.opam --deps-only --with-test

      - name: Build lwt package
        run: opam exec -- dune build -p azure-cosmos-db,azure-cosmos-db-lwt

  build-eio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.3"

      - name: Install eio dependencies
        run: opam install ./azure-cosmos-db.opam ./azure-cosmos-db-eio.opam --deps-only --with-test

      - name: Build eio package
        run: opam exec -- dune build -p azure-cosmos-db,azure-cosmos-db-eio

  test:
    needs: [build-core, build-lwt, build-eio]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.3"

      - name: Install all dependencies
        run: opam install . --deps-only --with-test

      - name: Run tests
        env:
          AZURE_COSMOS_KEY: ${{secrets.AZURE_COSMOS_KEY}}
          AZURE_COSMOS_ENDPOINT: ${{vars.AZURE_COSMOS_ENDPOINT}}
        run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - name: Upload coverage to coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PULL_REQUEST_NUMBER: ${{github.event.number}}
        run: |
          opam exec -- bisect-ppx-report coveralls coverage.json
          opam exec -- bisect-ppx-report send-to Coveralls
