name: Build and test

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "5.3"

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - if: ${{ matrix.ocaml-compiler == '5.3' }}
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PULL_REQUEST_NUMBER: ${{github.event.number}}
        run: |
          opam exec -- bisect-ppx-report coveralls coverage.json
          opam exec -- bisect-ppx-report send-to Coveralls
